trigger:
  branches:
    exclude:
      - '*'

pr:
  branches:
    include:
      - main

stages:
- stage: Build
  displayName: 'Build Stage'
  condition: eq(variables['Build.Reason'], 'PullRequest')
  jobs:
  - job: BuildJob
    steps:
    - script: echo "Building PR code..."
      displayName: 'Build PR'

- stage: Deploy
  displayName: 'Deploy Stage'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
  dependsOn: Build
  jobs:
  - job: DeployJob
    steps:
    - script: echo "Deploying after PR approval..."
      displayName: 'Deploy Code'
 
